## Linear Algebra

### LAB 4 ASSIGNMENT

#### TASK 1 - Matrix Operation



In [11]:
import numpy as np

# Representation of matrices using numpy
A = np.array([[2, -1], [0, 3]])
B = np.array([[1, 2], [-3, 4]])

print("Matrix A:")
print(A)
print(A.shape)

print("Matrix B:")
print(B)
print(B.shape)



Matrix A:
[[ 2 -1]
 [ 0  3]]
(2, 2)
Matrix B:
[[ 1  2]
 [-3  4]]
(2, 2)


##### a. A+B

In [12]:
C = A + B
print("Matrix A + B:")
print(C)

Matrix A + B:
[[ 3  1]
 [-3  7]]


##### b. AB

In [13]:
D = np.dot(A, B)  
print("Matrix AB (Product):")
print(D)


Matrix AB (Product):
[[ 5  0]
 [-9 12]]


##### c. 3A−2B

In [14]:
E= 3*A-2*B
print("Matrix 3A-2B:")
print(E)

Matrix 3A-2B:
[[ 4 -7]
 [ 6  1]]


#### TASK 2 -  Determinants and Inverses  

#####  Determinant of A.

In [15]:
import numpy.linalg as LA 
LA.det(A)

np.float64(6.0)

#####  Calculate A−1.

In [16]:
if LA.det(A) != 0:
    A_inv = LA.inv(A)
    print("Matrix A is invertible.")
    print("Determinant of A:", LA.det(A))
    print("Inverse of A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

Matrix A is invertible.
Determinant of A: 6.0
Inverse of A:
[[0.5        0.16666667]
 [0.         0.33333333]]


#### TASK 4 - Eigenvalues and Eigenvectors

#####  Eigenvalues and eigenvectors of the matrix: C=[[4    1], [​−2       1]​]

In [18]:
C = np.array([[4, 1], [-2, 1]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the results
print("Matrix C:")
print(C)
print("Eigenvalue:")
print(eigenvalues)
print(" Eigenvector:")
print(eigenvectors)

Matrix C:
[[ 4  1]
 [-2  1]]
Eigenvalue:
[2. 3.]
 Eigenvector:
[[ 1.         -0.70710678]
 [ 0.          0.70710678]]


#### TASK 4

In [26]:

X = np.array([[1, 4, 1.5, 100], [1, 6, 2.0, 150]])
y = np.array([20, 30])

beta = np.linalg.pinv(X.T @ X) @ X.T @ y

x3 = np.array([1, 8, 3.0, 200])

price_car3 = x3 @ beta

print("Coefficients (β):", beta)
print("Predicted price of car 3:", price_car3)


Coefficients (β): [-0.00079866  0.00798658  0.00159732  0.19966456]
Predicted price of car 3: 40.0007986582528
